---
- hosts:
   - brokers
   - zookeepers
   - zoonavigators
   - connects
   - ksqldbs
   - rest_proxies
   - schema_registries

  gather_facts: false
  # any_error_fatal: true
  become: true
  tasks:
      - name: "Test"
        ansible.builtin.command: sleep 20

      - name: "Test1"
        ansible.builtin.command: sleep 20